FileVersion = 1
Projects = {"Beef.Linq" = {Path = "src"}, "Befe.Linq.Tests" = {Path = "src/test"}}

[Configs.Test.Win32]
ConfigSelections = {corlib = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {corlib = {Config = "Debug"}}
